<a href="https://colab.research.google.com/github/Mengjie-Helen/IoT-Video-Classification/blob/main/Model_selection_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os
os.listdir('/content/drive/My Drive/Iot_Checkpoints/')

['SubSampled_Videos']

Featurization

In [ ]:
DATASET_no_interaction = '/content/drive/My Drive/Iot_Checkpoints/SubSampled_Videos/no_interaction_features'
os.listdir(DATASET_no_interaction)[:4]

['SubSampled_no_interaction_2_1616182454_1.mp4.npz',
 'SubSampled_no_interaction_9_1616182974_1.mp4.npz',
 'SubSampled_no_interaction_10_1616183029_1.mp4.npz',
 'SubSampled_no_interaction_5_1616182692_1.mp4.npz']

In [ ]:
%cd /content/drive/My Drive/Iot_Checkpoints/SubSampled_Videos/no_interaction_features
os.listdir('.')[:4]

/content/drive/.shortcut-targets-by-id/11uoUjnXa_0JKiMnhEb2WiTNyACQRegAl/Iot_Checkpoints/SubSampled_Videos/no_interaction_features


['SubSampled_no_interaction_2_1616182454_1.mp4.npz',
 'SubSampled_no_interaction_9_1616182974_1.mp4.npz',
 'SubSampled_no_interaction_10_1616183029_1.mp4.npz',
 'SubSampled_no_interaction_5_1616182692_1.mp4.npz']

In [ ]:
from glob import glob
result_no_interaction = [y for x in os.walk(DATASET_no_interaction) for y in glob(os.path.join(x[0], '*.npz'))]
videos_no_interaction = [r.split('/')[7] for r in result_no_interaction]

labels_no_interaction = []
for r in result_no_interaction:
    label_feature = r.split('/')[6]
    label = label_feature[:-9]
    labels_no_interaction.append(label)

In [ ]:
import numpy as np

In [ ]:
def extract_trajectories(keypoints):
  trajectory = []
  for _,k in keypoints:
    if len(k) !=0: #removes data where nothing is happening
      three_d_point = k[0,[0,1,3],:] #understand this code!!! look it up in the documentation
      trajectory.append(three_d_point)

  return trajectory

In [ ]:
data_no_interaction = []
result_no_interaction = []
for video in videos_no_interaction:
    data_no_interaction = np.load(video,allow_pickle = True)
    trajectory = extract_trajectories(data_no_interaction["keypoints"])
    result_no_interaction.append(trajectory)

In [ ]:
DATASET_open_close = '/content/drive/My Drive/Iot_Checkpoints/SubSampled_Videos/open_close_fridge_features'
os.listdir(DATASET_open_close)[:4]

['SubSampled_open_close_fridge_4_1613085604_1.mp4.npz',
 'SubSampled_open_close_fridge_5_1615392827_1.mp4.npz',
 'SubSampled_open_close_fridge_18_1615393749_1.mp4.npz',
 'SubSampled_open_close_fridge_1_1613680613_1.mp4.npz']

In [ ]:
%cd /content/drive/My Drive/Iot_Checkpoints/SubSampled_Videos/open_close_fridge_features
os.listdir('.')[:4]

/content/drive/.shortcut-targets-by-id/11uoUjnXa_0JKiMnhEb2WiTNyACQRegAl/Iot_Checkpoints/SubSampled_Videos/open_close_fridge_features


['SubSampled_open_close_fridge_4_1613085604_1.mp4.npz',
 'SubSampled_open_close_fridge_5_1615392827_1.mp4.npz',
 'SubSampled_open_close_fridge_18_1615393749_1.mp4.npz',
 'SubSampled_open_close_fridge_1_1613680613_1.mp4.npz']

In [ ]:
result_open_close = [y for x in os.walk(DATASET_open_close) for y in glob(os.path.join(x[0], '*.npz'))]
videos_open_close = [r.split('/')[7] for r in result_open_close]
labels_open_close = []
for r in result_open_close:
    label_feature = r.split('/')[6]
    label = label_feature[:-9]
    labels_open_close.append(label)

In [ ]:
data_open_close = []
result_open_close = []
for video in videos_open_close:
    data_open_close = np.load(video,allow_pickle = True)
    trajectory = extract_trajectories(data_open_close["keypoints"])
    result_open_close.append(trajectory)

In [ ]:
DATASET_put_back = '/content/drive/My Drive/Iot_Checkpoints/SubSampled_Videos/put_back_item_features'
os.listdir(DATASET_put_back)[:4]

['SubSampled_put_back_item_2_1613086149_1.mp4.npz',
 'SubSampled_put_back_item_4_1613086253_1.mp4.npz',
 'SubSampled_put_back_item_5_1613086310_1.mp4.npz',
 'SubSampled_put_back_item_1_1613086093_1.mp4.npz']

In [ ]:
%cd /content/drive/My Drive/Iot_Checkpoints/SubSampled_Videos/put_back_item_features
os.listdir('.')[:4]

/content/drive/.shortcut-targets-by-id/11uoUjnXa_0JKiMnhEb2WiTNyACQRegAl/Iot_Checkpoints/SubSampled_Videos/put_back_item_features


['SubSampled_put_back_item_2_1613086149_1.mp4.npz',
 'SubSampled_put_back_item_4_1613086253_1.mp4.npz',
 'SubSampled_put_back_item_5_1613086310_1.mp4.npz',
 'SubSampled_put_back_item_1_1613086093_1.mp4.npz']

In [ ]:
result_put_back = [y for x in os.walk(DATASET_put_back) for y in glob(os.path.join(x[0], '*.npz'))]
videos_put_back = [r.split('/')[7] for r in result_put_back]
labels_put_back = []
for r in result_put_back:
    label_feature = r.split('/')[6]
    label = label_feature[:-9]
    labels_put_back.append(label)

In [ ]:
data_put_back = []
result_put_back = []
for video in videos_put_back:
    data_put_back = np.load(video,allow_pickle = True)
    trajectory = extract_trajectories(data_put_back["keypoints"])
    result_put_back.append(trajectory)

In [ ]:
DATASET_screen_interaction = '/content/drive/My Drive/Iot_Checkpoints/SubSampled_Videos/screen_interaction_features'
os.listdir(DATASET_screen_interaction)[:4]

['SubSampled_screen_interaction_6_1616181758_1.mp4.npz',
 'SubSampled_screen_interaction_7_1616181874_1.mp4.npz',
 'SubSampled_screen_interaction_9_1616182093_1.mp4.npz',
 'SubSampled_screen_interaction_2_1616181306_1.mp4.npz']

In [ ]:
%cd /content/drive/My Drive/Iot_Checkpoints/SubSampled_Videos/screen_interaction_features
os.listdir('.')[:4]

/content/drive/.shortcut-targets-by-id/11uoUjnXa_0JKiMnhEb2WiTNyACQRegAl/Iot_Checkpoints/SubSampled_Videos/screen_interaction_features


['SubSampled_screen_interaction_6_1616181758_1.mp4.npz',
 'SubSampled_screen_interaction_7_1616181874_1.mp4.npz',
 'SubSampled_screen_interaction_9_1616182093_1.mp4.npz',
 'SubSampled_screen_interaction_2_1616181306_1.mp4.npz']

In [ ]:
result_screen_interaction = [y for x in os.walk(DATASET_screen_interaction) for y in glob(os.path.join(x[0], '*.npz'))]
videos_screen_interaction = [r.split('/')[7] for r in result_screen_interaction]
labels_screen_interaction = []
for r in result_screen_interaction:
    label_feature = r.split('/')[6]
    label = label_feature[:-9]
    labels_screen_interaction.append(label)

In [ ]:
data_screen_interaction = []
result_screen_interaction = []
for video in videos_screen_interaction:
    data_screen_interaction = np.load(video,allow_pickle = True)
    trajectory = extract_trajectories(data_screen_interaction["keypoints"])
    result_screen_interaction.append(trajectory)

In [ ]:
DATASET_take_out = '/content/drive/My Drive/Iot_Checkpoints/SubSampled_Videos/take_out_item_features'
os.listdir(DATASET_take_out)[:4]

['SubSampled_take_out_item_3_1616179525_1.mp4.npz',
 'SubSampled_take_out_item_10_1616180475_1.mp4.npz',
 'SubSampled_take_out_item_8_1616180240_1.mp4.npz',
 'SubSampled_take_out_item_5_1616180001_1.mp4.npz']

In [ ]:
%cd /content/drive/My Drive/Iot_Checkpoints/SubSampled_Videos/take_out_item_features
os.listdir('.')[:4]

/content/drive/.shortcut-targets-by-id/11uoUjnXa_0JKiMnhEb2WiTNyACQRegAl/Iot_Checkpoints/SubSampled_Videos/take_out_item_features


['SubSampled_take_out_item_3_1616179525_1.mp4.npz',
 'SubSampled_take_out_item_10_1616180475_1.mp4.npz',
 'SubSampled_take_out_item_8_1616180240_1.mp4.npz',
 'SubSampled_take_out_item_5_1616180001_1.mp4.npz']

In [ ]:
result_take_out = [y for x in os.walk(DATASET_take_out) for y in glob(os.path.join(x[0], '*.npz'))]
videos_take_out = [r.split('/')[7] for r in result_take_out]
labels_take_out = []
for r in result_take_out:
    label_feature = r.split('/')[6]
    label = label_feature[:-9]
    labels_take_out.append(label)

In [ ]:
data_take_out = []
result_take_out = []
for video in videos_take_out:
    data_take_out = np.load(video,allow_pickle = True)
    trajectory = extract_trajectories(data_take_out["keypoints"])
    result_take_out.append(trajectory)

In [ ]:
results = [result_no_interaction,result_open_close,result_put_back,result_screen_interaction,result_take_out]

In [ ]:
labels = [labels_no_interaction,labels_open_close,labels_put_back,labels_screen_interaction,labels_take_out]

**Split dataset**

Method 1: Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# Split
def create_dataset(X,Y):
    ''' CreateDataset: creates a training dataset and validation dataset
        Input: Directory with a collection of vectors of fixed dimension for each video
        Output: A training set (X_train,Y_train), a validation (X_test, Y_test)
        
    '''
    X_train = []
    X_test = []
    Y_train = []
    Y_test = []
    for i in range(len(X)):
        x_train,x_test,y_train,y_test = train_test_split(results[i],labels[i],test_size =0.3)
        for item in x_train:
            X_train.append(item)
        for item in y_train:
            Y_train.append(item)
        for item in x_test:
            X_test.append(item)
        for item in y_test:
            Y_test.append(item)

    maximum_x_train = float('-inf')
    for i in range(len(X_train)):
        n_x_train = np.array(X_train[i]).shape[0]
        maximum_x_train = max(maximum_x_train,n_x_train)
    maximum_x_test = float('-inf')
    for i in range(len(X_test)):
        n_x_test = np.array(X_test[i]).shape[0]
        maximum_x_test = max(maximum_x_train,n_x_test)

    if maximum_x_test < maximum_x_train:
        for i in range(len(X_test)):
            for m in range(len(X_test[i]),maximum_x_train+1):
                 print(np.array(X_test[i]).shape)
                 X_test[i].append(np.zeros((3,17)))
        for i in range(len(X_train)):
            for m in range(len(X_train[i]),maximum_x_train+1):
                 X_train[i].append(np.zeros((3,17)))
    else:
        for i in range(len(X_test)):
            for m in range(len(X_test[i]),maximum_x_test+1):
                 X_test[i].append(np.zeros((3,17)))
        for i in range(len(X_train)):
            for m in range(len(X_train[i]),maximum_x_test+1):
                 X_train[i].append(np.zeros((3,17)))
     
    return (X_train, Y_train), (X_test, Y_test)

In [ ]:
train, test = create_dataset(results,labels)

In [ ]:
X_train = train[0]
Y_train = train[1]
X_test = test[0]
Y_test = test[1]

In [ ]:
np.array(X_train).shape

(151, 103, 3, 17)

In [ ]:
np.array(X_test).shape

(67, 103, 3, 17)

In [ ]:
d2_train_dataset = np.array(X_train).reshape((151,103*3*17))

In [ ]:
d2_test_dataset = np.array(X_test).reshape((67,103*3*17))

**Decision Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dtree = DecisionTreeClassifier()

In [ ]:
dtree.fit(d2_train_dataset,Y_train)

DecisionTreeClassifier()

In [ ]:
predictions_1 = dtree.predict(d2_test_dataset)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
print(classification_report(Y_test,predictions_1))

                    precision    recall  f1-score   support

    no_interaction       0.62      0.56      0.59         9
 open_close_fridge       0.40      0.48      0.43        21
     put_back_item       0.11      0.09      0.10        11
screen_interaction       0.75      1.00      0.86         9
     take_out_item       0.31      0.24      0.27        17

          accuracy                           0.43        67
         macro avg       0.44      0.47      0.45        67
      weighted avg       0.41      0.43      0.41        67



In [ ]:
print(confusion_matrix(Y_test,predictions_1))

[[ 5  2  0  2  0]
 [ 1 10  4  0  6]
 [ 1  6  1  0  3]
 [ 0  0  0  9  0]
 [ 1  7  4  1  4]]


**Random Forest**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc = RandomForestClassifier(n_estimators=600)

In [ ]:
rfc.fit(d2_train_dataset,Y_train)

RandomForestClassifier(n_estimators=600)

In [ ]:
predictions_2 = rfc.predict(d2_test_dataset)

In [ ]:
print(classification_report(Y_test,predictions_2))

                    precision    recall  f1-score   support

    no_interaction       0.67      0.44      0.53         9
 open_close_fridge       0.71      0.71      0.71        21
     put_back_item       0.57      0.36      0.44        11
screen_interaction       0.67      0.89      0.76         9
     take_out_item       0.62      0.76      0.68        17

          accuracy                           0.66        67
         macro avg       0.65      0.64      0.63        67
      weighted avg       0.65      0.66      0.64        67



In [ ]:
print(confusion_matrix(Y_test,predictions_2))

[[ 4  2  0  3  0]
 [ 1 15  1  1  3]
 [ 1  2  4  0  4]
 [ 0  0  0  8  1]
 [ 0  2  2  0 13]]


**SVM**

In [ ]:
from sklearn.svm import SVC

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
param_grid = {'C': [0.1,1, 10, 100], 'gamma': [1,0.1,0.01,0.001]} 

In [ ]:
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=2)
grid.fit(d2_train_dataset,Y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] END .....................................C=0.1, gamma=1; total time=   0.1s
[CV] END .....................................C=0.1, gamma=1; total time=   0.1s
[CV] END .....................................C=0.1, gamma=1; total time=   0.1s
[CV] END .....................................C=0.1, gamma=1; total time=   0.1s
[CV] END .....................................C=0.1, gamma=1; total time=   0.1s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.1s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.1s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.1s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.1s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.1s
[CV] END ..................................C=0.1, gamma=0.01; total time=   0.1s
[CV] END ..................................C=0.1

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001]},
             verbose=2)

In [ ]:
grid_predictions = grid.predict(d2_test_dataset)

In [ ]:
print(classification_report(Y_test,grid_predictions))

                    precision    recall  f1-score   support

    no_interaction       0.00      0.00      0.00         9
 open_close_fridge       0.31      1.00      0.48        21
     put_back_item       0.00      0.00      0.00        11
screen_interaction       0.00      0.00      0.00         9
     take_out_item       0.00      0.00      0.00        17

          accuracy                           0.31        67
         macro avg       0.06      0.20      0.10        67
      weighted avg       0.10      0.31      0.15        67



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
